language: php
os: linux

php:
  - 8.0snapshot
  - master

env:
  - DEPS="LOW"
  - DEPS="NORMAL"

addons:
  apt:
    packages:
      - acl
      - python-docutils

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

stages:
  - static code analysis
  - test
  - test with coverage
  - build phar

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis.php.ini
  - phpenv rehash
  - set -e
  - pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
  - echo "=== SETTING GIT IDENTITY ==="
  - git config --global user.email "travis-ci-build@phing.info"
  - git config --global user.name "Phing Travis Builder"
  - composer self-update --2

install:
  - |
    if [[ "$DEPS" == "LOW" ]]; then
      composer install --prefer-dist --no-progress --no-interaction;
      composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --prefer-lowest;
    else
      composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction;
    fi

script:
  - echo "=== TESTING PHING ==="
  - cd test
  - ../bin/phing -verbose -Dtests.codecoverage=false -listener "phing.listener.StatisticsListener"
  - cd ..

jobs:
  allow_failures:
    - php: 8.0snapshot
    - php: master
  include:

    - stage: test with coverage
      php: 7.4
      env: DEPS="NORMAL"
      before_install:
        - phpenv config-add .travis.php.ini
        - phpenv config-add .travis.cov.php.ini
        - phpenv rehash
        - set -e
        - pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
        - echo "=== SETTING GIT IDENTITY ==="
        - git config --global user.email "travis-ci-build@phing.info"
        - git config --global user.name "Phing Travis Builder"
        - composer self-update --2
      script:
        - echo "=== TESTING PHING ==="
        - cd test
        - ../bin/phing -Dtests.codecoverage=true -listener "phing.listener.StatisticsListener"
        - cd ..
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./test/reports/clover-coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=clover ./test/reports/clover-coverage.xml

    - stage: static code analysis
      php: 7.4
      env: DEPS="NORMAL"
      script: bin/phpcs -s -n --standard=./ruleset.xml classes test/classes

    - stage: build phar
      php: 7.4
      env: DEPS="NORMAL"
      script:
        - cd build
        - ../bin/phing
        - php full/phing-$(cat ../etc/VERSION.TXT).phar -v

notifications:
  secure: "Q8xCtM0IMQyjQuPJOPFCcFvBUlD7zwg6E5vEFfsaFQj+9bJ83Xo3loURsizTBf+WpRruDxmu3tlg0GNk5yDt92POOCOISzyWPBDmHiy2MVDfINEwyNsJpzdlw1UnChoTjSwRS3goPivfQDkOsbSrszLE93iE9PIIUw5BV4CAoho="
