language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

env:
  - DEPS="LOW"
  - DEPS="NORMAL"

addons:
  apt:
    packages:
      - python-docutils

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

stages:
  - composer validate
  - static code analysis
  - test
  - test with coverage

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis.php.ini
  - phpenv rehash
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - set -e
  - pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
  - echo "=== SETTING GIT IDENTITY ==="
  - git config --global user.email "travis-ci-build@phing.info"
  - git config --global user.name "Phing Travis Builder"
  - composer self-update

install:
  - |
    if [[ "$DEPS" == "LOW" ]]; then
      composer install --prefer-dist --no-progress --no-interaction --no-suggest;
      composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --prefer-lowest;
    else
      composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction --no-suggest;
    fi

script:
  - echo "=== TESTING PHING ==="
  - cd test
  - ../bin/phing -Dtests.codecoverage=false -listener "phing.listener.StatisticsListener"
  - cd ..

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: master
    - php: nightly
  include:
    - php: nightly
      env: DEPS="IGNORE"
      install: composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --ignore-platform-reqs

    - stage: test with coverage
      php: 7.2
      env: DEPS="NORMAL"
      before_install:
        - phpenv config-add .travis.php.ini
        - phpenv rehash
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - set -e
        - pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
        - echo "=== SETTING GIT IDENTITY ==="
        - git config --global user.email "travis-ci-build@phing.info"
        - git config --global user.name "Phing Travis Builder"
        - composer self-update
      script:
        - echo "=== TESTING PHING ==="
        - cd test
        - ../bin/phing -Dtests.codecoverage=true -listener "phing.listener.StatisticsListener"
        - cd ..
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./test/reports/clover-coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=clover ./test/reports/clover-coverage.xml

    - stage: composer validate
      os: linux
      php: 7.2
      env: DEPS="NORMAL"
      script:
        - composer validate

    - stage: static code analysis
      os: linux
      php: 7.2
      env: DEPS="NORMAL"
      script: bin/phpcs -n --standard=./ruleset.xml classes

notifications:
  secure: "Q8xCtM0IMQyjQuPJOPFCcFvBUlD7zwg6E5vEFfsaFQj+9bJ83Xo3loURsizTBf+WpRruDxmu3tlg0GNk5yDt92POOCOISzyWPBDmHiy2MVDfINEwyNsJpzdlw1UnChoTjSwRS3goPivfQDkOsbSrszLE93iE9PIIUw5BV4CAoho="
