language: php

sudo: false

addons:
  apt:
    packages:
      - acl
      - python-docutils

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

install:
  - |
    set -e
    pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
    if [[ "$DEPS" == "LOW" ]]; then
      composer install -n;
      composer update --prefer-lowest;
    else
      composer install -o --no-progress --prefer-dist;
    fi
    phpenv config-add .travis.php.ini;
    phpenv rehash;
    echo "=== SETTING GIT IDENTITY ===";
    git config --global user.email "travis-ci-build@phing.info";
    git config --global user.name "Phing Travis Builder";
script:
  - |
    if [[ "$PHPCS" == "TRUE" ]]; then
      bin/phpcs -n --standard=./ruleset.xml classes
    else
      echo "=== TESTING PHING ==="
      cd test
      ../bin/phing -Dtests.codecoverage=true -listener "phing.listener.StatisticsListener"
      cd ..
    fi
after_success:
  - |
    if [[ "$PHPCS" != "TRUE" ]]; then
      if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        bash <(curl -s https://codecov.io/bash)
      fi
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=clover ./test/reports/clover-coverage.xml
    fi

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

matrix:
  include:
    - php: 7.2
      env: PHPCS="TRUE"
    - php: 7.1
      env: DEPS="LOW"
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: master

notifications:
  secure: "Q8xCtM0IMQyjQuPJOPFCcFvBUlD7zwg6E5vEFfsaFQj+9bJ83Xo3loURsizTBf+WpRruDxmu3tlg0GNk5yDt92POOCOISzyWPBDmHiy2MVDfINEwyNsJpzdlw1UnChoTjSwRS3goPivfQDkOsbSrszLE93iE9PIIUw5BV4CAoho="
